name: Deploy to DigitalOcean

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: ${{ github.event.repository.name  }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519  #Add local private key to Github action secret. local public key to server
          chmod 600 ~/.ssh/id_ed25519
          printf "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      - name: Deploy over SSH
        run: |
          ssh ${{ secrets.SERVER_USER }} << EOF
            set -xe
      
            SERVICE_NAME=${{ github.event.repository.name }}
      
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u doodaadennis --password-stdin
      
            cd /var/www/dennisapplebaum
      
            docker compose pull 
            docker compose stop  "$SERVICE_NAME" || true
            docker compose rm "$SERVICE_NAME" || true
            docker compose --profile "$SERVICE_NAME" up -d
          EOF
